# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7e027c9ecb7987c7a1ac3af0781cb929eb532083016ae1efbc511087d1b5db2eabddb40678b34d51d43cc3ac8888b9aac3ea970861de1d45ac1374bb671567

test:
  secret_key_base: dec570a6017684c77aae27d7908d4dfa50d1f19821da51345f7220df5bdb815e0c578958cd7896899950d0be09ab7bc67a66e517f46ad23a30e72d7be33734dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
